apiVersion: v1
kind: Pod
metadata:
  name: mimir-alertmanager-test
  namespace: monitoring
spec:
  containers:
  - command:
    - sleep
    - infinity
    # args:
    # - -target=alertmanager
    # - -config.expand-env=true
    # - -config.file=/etc/mimir/mimir.yaml
    env:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: eu-north-1
    - name: AWS_REGION
      value: eu-north-1
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: grafana/mimir:2.12.0
    imagePullPolicy: IfNotPresent
    name: alertmanager
    ports:
    - containerPort: 8080
      name: http-metrics
      protocol: TCP
    - containerPort: 9095
      name: grpc
      protocol: TCP
    - containerPort: 7946
      name: memberlist
      protocol: TCP
    resources:
      limits:
        memory: 1G
        cpu: "1"
      requests:
        cpu: 10m
        memory: 32Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /templates/
      name: alertmanager-templates
    - mountPath: /etc/mimir
      name: config
    - mountPath: /var/mimir
      name: runtime-config
    - mountPath: /configs/
      name: alertmanager-fallback-config
    - mountPath: /tmp
      name: tmp
    - mountPath: /active-query-tracker
      name: active-queries
  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: false
    runAsUser: 0
  serviceAccount: mimir
  serviceAccountName: mimir
  volumes:
  - configMap:
      items:
      - key: mimir.yaml
        path: mimir.yaml
      name: mimir-config
    name: config
  - configMap:
      name: mimir-runtime
    name: runtime-config
  - emptyDir: {}
    name: tmp
  - emptyDir: {}
    name: active-queries
  - configMap:
      name: mimir-alertmanager-fallback-config
    name: alertmanager-fallback-config
  - configMap:
      name: mimir-alertmanager-templates
    name: alertmanager-templates
